CREATE TABLE IF NOT EXISTS exercise (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    muscle_group VARCHAR(255),
    primary_group VARCHAR(255),
    default_weight INT
);

INSERT INTO exercise (name, muscle_group, primary_group, default_weight) VALUES
  ('Supinated Bicep Curls', 'BICEPS', 'PULL', 15),
  ('EZ Bar Curl', 'BICEPS', 'PULL', 20),
  ('Bayesian Curls', 'BICEPS', 'PULL', 12.5),
  ('Seated Incline Curls', 'BICEPS', 'PULL', 12.5),
  ('Preacher Curls', 'BICEPS', 'PULL', 12.5),
  ('Cable Curls', 'BICEPS', 'PULL', 27.5),
  ('Concentration Curls', 'BICEPS', 'PULL', 15),
  ('Cable Reverse Curls', 'BRACHIORADIALIS', 'PULL', 22.5),
  ('Cable Hammer Curls', 'BRACHIORADIALIS', 'PULL', 22.5),
  ('Dumbbell Hammer Curls', 'BRACHIORADIALIS', 'PULL', 17.5),
  ('Upwards Cable Wrist Curls', 'FOREARMS', 'PULL', 7.5),
  ('Downwards Cable Wrist Curls', 'FOREARMS', 'PULL', 15),
  ('Lat Pulldown', 'LATS', 'PULL', 65),
  ('Assisted Pull Ups', 'LATS', 'PULL', 21),
  ('Vertical Traction', 'LATS', 'PULL', 75),
  ('Pulley', 'RHOMBOIDS', 'PULL', 45),
  ('Pulley Single Arm', 'RHOMBOIDS', 'PULL', 15),
  ('Bent Over Rows', 'RHOMBOIDS', 'PULL', 15),
  ('Back Row Machine', 'REARDELTS', 'PULL', 55),
  ('Bent Over Dumbbell Flies', 'REARDELTS', 'PULL', 15),
  ('Barbell Bench Press', 'CHEST', 'PUSH', 50),
  ('Incline Barbell Bench Press', 'CHEST', 'PUSH', 40),
  ('Chest Press Machine', 'CHEST', 'PUSH', 80),
  ('Dumbbell Chest Press', 'CHEST', 'PUSH', 27.5),
  ('Dumbbell Chest Fly', 'CHEST', 'PUSH', 22.5),
  ('Cable Crossover', 'CHEST', 'PUSH', 15),
  ('Dumbbell Shoulder Press', 'FRONTDELTS', 'PUSH', 20),
  ('Shoulder Press Machine', 'FRONTDELTS', 'PUSH', 35),
  ('Dumbbell Front Raises', 'FRONTDELTS', 'PUSH', 15),
  ('Dumbbell Lateral Raises', 'SIDEDELTS', 'PUSH', 10),
  ('Cable Lateral Raises', 'SIDEDELTS', 'PUSH', 10),
  ('Dumbbell Shrugs', 'TRAPS', 'PUSH', 32.5),
  ('Cable Single Arm Pulldown', 'TRICEPSLATERAL', 'PUSH', 12.5),
  ('Cable Bar Pulldown', 'TRICEPSLATERAL', 'PUSH', 32.5),
  ('Cable Bar Overhead', 'TRICEPSLONG', 'PUSH', 32.5),
  ('Dumbbell Skullcrushers', 'TRICEPSLONG', 'PUSH', 12.5),
  ('Assisted Dips', 'TRICEPSLONG', 'PUSH', 28),
  ('Leg Press', 'QUADS', 'LEGS', 110),
  ('Leg Curl', 'HAMSTRINGS', 'LEGS', 55),
  ('Leg Extensions', 'QUADS', 'LEGS', 55),
  ('Hip Abductor', 'GLUTES', 'LEGS', 50),
  ('Hip Adductor', 'GLUTES', 'LEGS', 50),
  ('Hip Thrust', 'GLUTES', 'LEGS', 25);
 
